import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'
import { volumeFragment, volumeVertex } from './volumeShaders'

export type FieldMode='composite'|'theta'|'moisture'|'vorticity'|'coldpool'
export type SurfaceType='grass'|'dry'|'water'|'urban'
export interface SimConfig{
  surfaceTemp:number;lapseLow:number;lapseMid:number;lapseUpper:number;tropopause:number;stratoWarming:number
  rhSurface:number;rhLow:number;rhMid:number;rhUpper:number;entrainment:number
  wind0:number;wind3:number;wind6:number;wind10:number;windDir0:number;windDir3:number;windDir6:number;windDir10:number
  latitude:number;turbulence:number;hour:number;solarMax:number;soilMoisture:number;surfaceType:SurfaceType
  precipEfficiency:number;evaporation:number;coldPoolStrength:number;speed:number;seed:number
}
export interface ParcelPoint{z:number;env:number;parcel:number;buoyancy:number}

const NX=40,NY=32,NZ=24,N=NX*NY*NZ,W=48_000,D=36_000,H=15_000,DX=W/NX,DY=D/NY,DZ=H/(NZ-1)
const G=9.81,CP=1004,LV=2.5e6,KAPPA=.286,RD=287.05,EPS=.622,OMEGA=7.2921e-5,DT=1
const FLOW_PARTICLES=10_000,SUN_POSITION=new THREE.Vector3(-25,45,18)
const clamp=(x:number,a=0,b=1)=>Math.max(a,Math.min(b,x)),lerp=(a:number,b:number,t:number)=>a+(b-a)*clamp(t)
const mod=(x:number,n:number)=>((x%n)+n)%n
const softParticleTexture=()=>{const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d')!,g=x.createRadialGradient(32,32,2,32,32,31);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.42,'rgba(255,255,255,.78)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,64,64);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}

export class Atmosphere{
  private canvas:HTMLCanvasElement;private config:SimConfig;private renderer:THREE.WebGLRenderer;private scene:THREE.Scene;private camera:THREE.PerspectiveCamera;private controls:OrbitControls
  private ground:THREE.Mesh;private raycaster=new THREE.Raycaster();private pointer=new THREE.Vector2()
  private volumeData=new Uint8Array(N*2);private volumeTexture:THREE.Data3DTexture;private volumeMaterial:THREE.ShaderMaterial;private volumeMesh:THREE.Mesh;private flowGeometry:THREE.BufferGeometry;private flowPoints:THREE.Points;private vectorGeometry:THREE.BufferGeometry;private vectorLines:THREE.LineSegments;private fieldGeometry:THREE.BufferGeometry;private fieldPoints:THREE.Points
  private levelHelpers:THREE.GridHelper[]=[]
  private u=new Float32Array(N);private v=new Float32Array(N);private w=new Float32Array(N);private theta=new Float32Array(N);private q=new Float32Array(N);private cloud=new Float32Array(N);private rain=new Float32Array(N);private cold=new Float32Array(N)
  private pressure=new Float32Array(N);private divergence=new Float32Array(N);private scratch=new Float32Array(N);private surfacePattern=new Float32Array(NX*NY)
  private particleModel=new Float32Array(FLOW_PARTICLES*3);private particleAge=new Float32Array(FLOW_PARTICLES);private rng:()=>number;private accumulator=0;private microburstOutflow=0;private frame=0
  private cachedParcel:{profile:ParcelPoint[];cape:number;cin:number;lcl:number|null;lfc:number|null;el:number|null}
  field:FieldMode='composite';showVectors=false;time=0

  constructor(canvas:HTMLCanvasElement,config:SimConfig){
    this.canvas=canvas;this.config=config;this.rng=this.mulberry32(config.seed);this.cachedParcel={profile:[],cape:0,cin:0,lcl:null,lfc:null,el:null}
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x172d3b);this.scene.fog=new THREE.FogExp2(0x172d3b,.012)
    this.camera=new THREE.PerspectiveCamera(42,1,.1,180);this.camera.position.set(38,24,39)
    this.controls=new OrbitControls(this.camera,canvas);this.controls.target.set(0,6,0);this.controls.enableDamping=true;this.controls.dampingFactor=.07;this.controls.maxPolarAngle=Math.PI*.495;this.controls.minDistance=15;this.controls.maxDistance=100
    this.scene.add(new THREE.HemisphereLight(0xd9efff,0x4b4439,1.35));const sun=new THREE.DirectionalLight(0xfff0d2,2);sun.position.copy(SUN_POSITION);this.scene.add(sun)
    const groundMat=new THREE.MeshStandardMaterial({color:this.surfaceColor(),roughness:.96,metalness:0});this.ground=new THREE.Mesh(new THREE.PlaneGeometry(W/1000,D/1000),groundMat);this.ground.rotation.x=-Math.PI/2;this.scene.add(this.ground)
    const grid=new THREE.GridHelper(W/1000,16,0x71838a,0x485d66);grid.material.transparent=true;grid.material.opacity=.32;this.scene.add(grid)
    const box=new THREE.BoxGeometry(W/1000,H/1000,D/1000);box.translate(0,H/2000,0);const edges=new THREE.LineSegments(new THREE.EdgesGeometry(box),new THREE.LineBasicMaterial({color:0x75909c,transparent:true,opacity:.4}));this.scene.add(edges)
    this.levelHelpers=[0xb6d4dd,0xe1bf7e,0xd88e74].map(color=>{const h=new THREE.GridHelper(W/1000,12,color,color);h.material.transparent=true;h.material.opacity=.18;this.scene.add(h);return h})
    this.volumeTexture=new THREE.Data3DTexture(this.volumeData,NX,NY,NZ);this.volumeTexture.format=THREE.RGFormat;this.volumeTexture.type=THREE.UnsignedByteType;this.volumeTexture.minFilter=this.volumeTexture.magFilter=THREE.LinearFilter;this.volumeTexture.wrapS=this.volumeTexture.wrapT=THREE.RepeatWrapping;this.volumeTexture.wrapR=THREE.ClampToEdgeWrapping;this.volumeTexture.unpackAlignment=1;this.volumeTexture.needsUpdate=true
    this.volumeMaterial=new THREE.ShaderMaterial({vertexShader:volumeVertex,fragmentShader:volumeFragment,side:THREE.BackSide,transparent:true,depthWrite:false,depthTest:false,premultipliedAlpha:true,uniforms:{
      uDensity:{value:this.volumeTexture},uBoxMin:{value:new THREE.Vector3(-W/2000,0,-D/2000)},uBoxMax:{value:new THREE.Vector3(W/2000,H/1000,D/2000)},uGrid:{value:new THREE.Vector3(NX,NY,NZ)},
      uSunDir:{value:SUN_POSITION.clone().normalize()},uSunColor:{value:new THREE.Color(1,.94,.84).multiplyScalar(2.6)},uFogColor:{value:(this.scene.fog as THREE.FogExp2).color},uFogDensity:{value:(this.scene.fog as THREE.FogExp2).density},
      uHeight:{value:H/1000},uTime:{value:0},uExtinction:{value:2.2}}})
    const volumeBox=new THREE.BoxGeometry(W/1000,H/1000,D/1000);volumeBox.translate(0,H/2000,0);this.volumeMesh=new THREE.Mesh(volumeBox,this.volumeMaterial);this.volumeMesh.renderOrder=1;this.scene.add(this.volumeMesh)
    const soft=softParticleTexture()
    this.flowGeometry=new THREE.BufferGeometry();this.flowGeometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(FLOW_PARTICLES*3),3));this.flowGeometry.setAttribute('color',new THREE.BufferAttribute(new Float32Array(FLOW_PARTICLES*3),3));this.flowPoints=new THREE.Points(this.flowGeometry,new THREE.PointsMaterial({size:.12,map:soft,alphaTest:.03,vertexColors:true,transparent:true,opacity:.82,depthWrite:false}));this.flowPoints.renderOrder=2;this.scene.add(this.flowPoints)
    this.vectorGeometry=new THREE.BufferGeometry();this.vectorGeometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(1800*3),3));this.vectorGeometry.setAttribute('color',new THREE.BufferAttribute(new Float32Array(1800*3),3));this.vectorLines=new THREE.LineSegments(this.vectorGeometry,new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.72}));this.scene.add(this.vectorLines)
    const voxelCount=Math.ceil(NX/2)*Math.ceil(NY/2)*Math.ceil(NZ/2);this.fieldGeometry=new THREE.BufferGeometry();this.fieldGeometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(voxelCount*3),3));this.fieldGeometry.setAttribute('color',new THREE.BufferAttribute(new Float32Array(voxelCount*3),3));this.fieldPoints=new THREE.Points(this.fieldGeometry,new THREE.PointsMaterial({size:.32,vertexColors:true,transparent:true,opacity:.58,depthWrite:false}));this.scene.add(this.fieldPoints)
    this.initialize();this.cachedParcel=this.computeParcel();this.updateLevels();for(let p=0;p<FLOW_PARTICLES;p++)this.respawnParticle(p,true)
  }

  dispose(){this.controls.dispose();this.volumeTexture.dispose();this.volumeMaterial.dispose();this.volumeMesh.geometry.dispose();this.renderer.dispose()}
  private surfaceColor(){return{grass:0x596d45,dry:0x776a51,water:0x315d70,urban:0x606469}[this.config.surfaceType]}
  private idx(x:number,y:number,z:number){return mod(x,NX)+NX*(mod(y,NY)+NY*clamp(z,0,NZ-1))}
  private mulberry32(seed:number){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
  private pressureAt(z:number){return 101325*Math.exp(-z/8000)}
  private temperatureEnv(z:number){const tp=this.config.tropopause*1000,t3=this.config.surfaceTemp-this.config.lapseLow*3,t8=t3-this.config.lapseMid*5;if(z<=3000)return this.config.surfaceTemp-this.config.lapseLow*z/1000;if(z<=8000)return t3-this.config.lapseMid*(z-3000)/1000;const ttp=t8-this.config.lapseUpper*(tp-8000)/1000;if(z<=tp)return t8-this.config.lapseUpper*(z-8000)/1000;return ttp+this.config.stratoWarming*(z-tp)/1000}
  private thetaEnv(z:number){return(this.temperatureEnv(z)+273.15)*(100000/this.pressureAt(z))**KAPPA}
  private tempFromTheta(th:number,z:number){return th*(this.pressureAt(z)/100000)**KAPPA-273.15}
  private qsat(t:number,z:number){const es=611.2*Math.exp(17.67*t/(t+243.5));return clamp(.622*es/Math.max(1000,this.pressureAt(z)-es),0,.045)}
  private rhEnv(z:number){const tp=this.config.tropopause*1000;if(z<1500)return lerp(this.config.rhSurface,this.config.rhLow,z/1500)/100;if(z<5000)return lerp(this.config.rhLow,this.config.rhMid,(z-1500)/3500)/100;if(z<tp)return lerp(this.config.rhMid,this.config.rhUpper,(z-5000)/Math.max(1000,tp-5000))/100;return this.config.rhUpper/100*.7}
  private qEnv(z:number){return this.rhEnv(z)*this.qsat(this.temperatureEnv(z),z)}
  private windScalar(z:number){if(z<3000)return lerp(this.config.wind0,this.config.wind3,z/3000);if(z<6000)return lerp(this.config.wind3,this.config.wind6,(z-3000)/3000);if(z<10000)return lerp(this.config.wind6,this.config.wind10,(z-6000)/4000);return this.config.wind10}
  private windDirection(z:number){if(z<3000)return lerp(this.config.windDir0,this.config.windDir3,z/3000);if(z<6000)return lerp(this.config.windDir3,this.config.windDir6,(z-3000)/3000);if(z<10000)return lerp(this.config.windDir6,this.config.windDir10,(z-6000)/4000);return this.config.windDir10}
  private windUV(z:number){const s=this.windScalar(z),a=(270-this.windDirection(z))*Math.PI/180;return[s*Math.cos(a),s*Math.sin(a)] as const}
  private surface(){return{grass:{albedo:.2,sensible:.42,evap:.75,inertia:.65},dry:{albedo:.3,sensible:.72,evap:.15,inertia:.45},water:{albedo:.08,sensible:.18,evap:1.25,inertia:1.8},urban:{albedo:.16,sensible:.78,evap:.08,inertia:.8}}[this.config.surfaceType]}
  private insolation(){const hour=this.config.hour+this.time/3600;return this.config.solarMax*Math.max(0,Math.sin(Math.PI*(hour-6)/12))}

  private initialize(){let walk=0;for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){walk=walk*.82+(this.rng()-.5)*.34;this.surfacePattern[x+NX*y]=walk}for(let z=0;z<NZ;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const i=this.idx(x,y,z),alt=z*DZ,[ue,ve]=this.windUV(alt);this.u[i]=ue;this.v[i]=ve;this.w[i]=0;this.theta[i]=this.thetaEnv(alt)+(this.rng()-.5)*.018;this.q[i]=this.qEnv(alt);this.cloud[i]=this.rain[i]=this.cold[i]=0}this.injectBubble(W*.38,D*.45,1);this.injectBubble(W*.61,D*.57,.72)}
  private injectBubble(cx:number,cy:number,strength:number){for(let z=0;z<Math.min(5,NZ);z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){let dx=x*DX-cx,dy=y*DY-cy;if(dx>W/2)dx-=W;if(dx<-W/2)dx+=W;if(dy>D/2)dy-=D;if(dy<-D/2)dy+=D;const d2=(dx/4200)**2+(dy/4200)**2+(z*DZ/1800)**2,a=Math.exp(-d2)*strength,i=this.idx(x,y,z);this.theta[i]+=3.2*a;this.q[i]+=.003*a;this.w[i]+=1.1*a}}
  perturb(nx:number,ny:number,strength=1){this.pointer.set(nx*2-1,-(ny*2-1));this.raycaster.setFromCamera(this.pointer,this.camera);const hit=this.raycaster.intersectObject(this.ground,false)[0];const cx=hit?clamp((hit.point.x+W/2000)*1000,0,W):W/2,cy=hit?clamp((hit.point.z+D/2000)*1000,0,D):D/2;this.injectBubble(cx,cy,strength)}

  private sample(a:Float32Array,x:number,y:number,z:number){x=mod(x,NX);y=mod(y,NY);z=clamp(z,0,NZ-1.001);const x0=Math.floor(x),y0=Math.floor(y),z0=Math.floor(z),x1=(x0+1)%NX,y1=(y0+1)%NY,z1=Math.min(NZ-1,z0+1),fx=x-x0,fy=y-y0,fz=z-z0;const c000=a[this.idx(x0,y0,z0)],c100=a[this.idx(x1,y0,z0)],c010=a[this.idx(x0,y1,z0)],c110=a[this.idx(x1,y1,z0)],c001=a[this.idx(x0,y0,z1)],c101=a[this.idx(x1,y0,z1)],c011=a[this.idx(x0,y1,z1)],c111=a[this.idx(x1,y1,z1)],c00=lerp(c000,c100,fx),c10=lerp(c010,c110,fx),c01=lerp(c001,c101,fx),c11=lerp(c011,c111,fx);return lerp(lerp(c00,c10,fy),lerp(c01,c11,fy),fz)}
  private advect(a:Float32Array,dt:number,decay=1,fall=0){for(let z=0;z<NZ;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const i=this.idx(x,y,z);this.scratch[i]=this.sample(a,x-this.u[i]*dt/DX,y-this.v[i]*dt/DY,z-(this.w[i]-fall)*dt/DZ)*decay}a.set(this.scratch)}
  advance(realDt:number){this.accumulator+=realDt*this.config.speed;let steps=0;while(this.accumulator>=DT&&steps<12){this.step(DT);this.accumulator-=DT;this.time+=DT;steps++}}
  private step(dt:number){
    this.microburstOutflow*=.993;this.advect(this.u,dt,.9999);this.advect(this.v,dt,.9999);this.advect(this.w,dt,.9995);this.advect(this.theta,dt);this.advect(this.q,dt,.999999);this.advect(this.cloud,dt,.99995);this.advect(this.rain,dt,.9995,7);this.advect(this.cold,dt,.9992)
    const surf=this.surface(),solar=this.insolation(),absorbed=solar*(1-surf.albedo),heatFlux=absorbed*surf.sensible/surf.inertia,moistFlux=absorbed*(1-surf.sensible)*surf.evap*this.config.soilMoisture/100,lfcZ=(this.cachedParcel.lfc??1.5)*1000,f=2*OMEGA*Math.sin(this.config.latitude*Math.PI/180)
    for(let z=0;z<NZ;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){
      const i=this.idx(x,y,z),alt=z*DZ,p=this.pressureAt(alt),exner=(p/100000)**KAPPA,temp=this.tempFromTheta(this.theta[i],alt),sat=this.qsat(temp,alt),rh=this.q[i]/Math.max(.00001,sat)
      if(this.q[i]>sat){const cond=Math.min(this.q[i]-sat,(this.q[i]-sat)*.32*dt);this.q[i]-=cond;this.cloud[i]+=cond;this.theta[i]+=LV/CP/exner*cond}
      if(rh<1&&this.cloud[i]>0){const evap=Math.min(this.cloud[i],.00006*this.config.entrainment*(1-rh)*dt);this.cloud[i]-=evap;this.q[i]+=evap;const cool=LV/CP/exner*evap;this.theta[i]-=cool;this.cold[i]+=cool*.14}
      const auto=Math.max(0,this.cloud[i]-.0009)*.035*this.config.precipEfficiency*dt;this.cloud[i]-=auto;this.rain[i]+=auto
      if(this.q[i]<sat&&this.rain[i]>0){const evap=Math.min(this.rain[i],(sat-this.q[i])*.018*this.config.evaporation*dt);this.rain[i]-=evap;this.q[i]+=evap;const cool=LV/CP/exner*evap*this.config.coldPoolStrength;this.theta[i]-=cool;this.cold[i]+=cool}
      const buoy=(this.theta[i]-this.thetaEnv(alt))/Math.max(250,this.thetaEnv(alt))+.61*(this.q[i]-this.qEnv(alt))-1.8*this.cloud[i]-2.5*this.rain[i];this.w[i]+=G*buoy*dt
      const[ue,ve]=this.windUV(alt),du=this.u[i]-ue,dv=this.v[i]-ve;this.u[i]+=f*dv*dt;this.v[i]-=f*du*dt
      if(z<=1){const weight=Math.exp(-alt/300),pattern=1+this.surfacePattern[x+NX*y]*.32,rho=1.18*Math.exp(-alt/9000);this.theta[i]+=heatFlux*pattern/(rho*CP*300)*weight*dt;this.q[i]+=moistFlux*1.3e-10*weight*dt}
      if(alt<Math.min(3200,lfcZ)){const s=this.idx(x,y,0),gx=this.cold[this.idx(x+1,y,0)]-this.cold[this.idx(x-1,y,0)],gy=this.cold[this.idx(x,y+1,0)]-this.cold[this.idx(x,y-1,0)],edge=Math.hypot(gx,gy),core=this.cold[s];this.w[i]+=G*edge/300*.45*this.config.coldPoolStrength*Math.max(.12,1-alt/Math.max(300,lfcZ))*dt;if(alt<1300&&core>1)this.w[i]-=G*core/300*.52*Math.exp(-alt/520)*dt}
      if(z<=1&&this.w[i]<-5&&this.rain[i]>.0001){const impact=Math.min(38,-this.w[i]*Math.sqrt(this.rain[i]/.00055))*this.config.precipEfficiency,dpx=(-this.w[this.idx(x+1,y,z)]+this.w[this.idx(x-1,y,z)])*.5,dpy=(-this.w[this.idx(x,y+1,z)]+this.w[this.idx(x,y-1,z)])*.5;this.u[i]-=dpx*.12*dt;this.v[i]-=dpy*.12*dt;this.cold[i]+=impact*.0012*dt;this.microburstOutflow=Math.max(this.microburstOutflow,impact)}
      const mix=clamp(this.config.turbulence*.0015*dt,0,.01);const thAvg=(this.theta[this.idx(x+1,y,z)]+this.theta[this.idx(x-1,y,z)]+this.theta[this.idx(x,y+1,z)]+this.theta[this.idx(x,y-1,z)])/4;this.theta[i]=lerp(this.theta[i],thAvg,mix);const qAvg=(this.q[this.idx(x+1,y,z)]+this.q[this.idx(x-1,y,z)]+this.q[this.idx(x,y+1,z)]+this.q[this.idx(x,y-1,z)])/4;this.q[i]=lerp(this.q[i],qAvg,mix);this.cold[i]=clamp(this.cold[i],0,15)
      const spongeStart=Math.max(this.config.tropopause*1000+1600,13_000);if(alt>spongeStart){const s=clamp((alt-spongeStart)/(H-spongeStart))*.06*dt;this.w[i]*=1-s;this.u[i]=lerp(this.u[i],ue,s);this.v[i]=lerp(this.v[i],ve,s);this.theta[i]=lerp(this.theta[i],this.thetaEnv(alt),s)}
    }
    this.project(dt,16);for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const b=this.idx(x,y,0),t=this.idx(x,y,NZ-1);this.w[b]=0;this.u[b]*=.94;this.v[b]*=.94;this.w[t]=0}
    this.updateParticles(dt)
  }
  private project(dt:number,iters:number){this.pressure.fill(0);const ix=1/(DX*DX),iy=1/(DY*DY),iz=1/(DZ*DZ),den=2*(ix+iy+iz);for(let z=1;z<NZ-1;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const i=this.idx(x,y,z);this.divergence[i]=(this.u[this.idx(x+1,y,z)]-this.u[this.idx(x-1,y,z)])/(2*DX)+(this.v[this.idx(x,y+1,z)]-this.v[this.idx(x,y-1,z)])/(2*DY)+(this.w[this.idx(x,y,z+1)]-this.w[this.idx(x,y,z-1)])/(2*DZ)}for(let k=0;k<iters;k++)for(let z=1;z<NZ-1;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const i=this.idx(x,y,z);this.pressure[i]=((this.pressure[this.idx(x+1,y,z)]+this.pressure[this.idx(x-1,y,z)])*ix+(this.pressure[this.idx(x,y+1,z)]+this.pressure[this.idx(x,y-1,z)])*iy+(this.pressure[this.idx(x,y,z+1)]+this.pressure[this.idx(x,y,z-1)])*iz-this.divergence[i]/dt)/den}for(let z=1;z<NZ-1;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const i=this.idx(x,y,z);this.u[i]-=dt*(this.pressure[this.idx(x+1,y,z)]-this.pressure[this.idx(x-1,y,z)])/(2*DX);this.v[i]-=dt*(this.pressure[this.idx(x,y+1,z)]-this.pressure[this.idx(x,y-1,z)])/(2*DY);this.w[i]-=dt*(this.pressure[this.idx(x,y,z+1)]-this.pressure[this.idx(x,y,z-1)])/(2*DZ);this.u[i]=clamp(this.u[i],-85,85);this.v[i]=clamp(this.v[i],-85,85);this.w[i]=clamp(this.w[i],-60,60)}}

  private respawnParticle(p:number,full=false){const j=p*3;this.particleModel[j]=this.rng()*W;this.particleModel[j+1]=this.rng()*D;this.particleModel[j+2]=full?this.rng()*H*.75:this.rng()*1800;this.particleAge[p]=this.rng()*500}
  private updateParticles(dt:number){const pos=this.flowGeometry.getAttribute('position') as THREE.BufferAttribute,col=this.flowGeometry.getAttribute('color') as THREE.BufferAttribute;for(let p=0;p<FLOW_PARTICLES;p++){const j=p*3;let x=this.particleModel[j],y=this.particleModel[j+1],z=this.particleModel[j+2],gx=x/DX,gy=y/DY,gz=z/DZ,uu=this.sample(this.u,gx,gy,gz),vv=this.sample(this.v,gx,gy,gz),ww=this.sample(this.w,gx,gy,gz);x=mod(x+uu*dt,W);y=mod(y+vv*dt,D);z+=ww*dt;this.particleAge[p]+=dt;if(z<0||z>H||this.particleAge[p]>900){this.respawnParticle(p);x=this.particleModel[j];y=this.particleModel[j+1];z=this.particleModel[j+2]}else{this.particleModel[j]=x;this.particleModel[j+1]=y;this.particleModel[j+2]=z}pos.setXYZ(p,x/1000-W/2000,z/1000,y/1000-D/2000);if(ww>1)col.setXYZ(p,1,.5,.18);else if(ww<-1)col.setXYZ(p,.25,.62,1);else col.setXYZ(p,.72,.82,.86)}pos.needsUpdate=true;col.needsUpdate=true}
  private updateVolume(){const d=this.volumeData;for(let i=0;i<N;i++){d[i*2]=clamp((this.cloud[i]-.00003)/.0014)*255;d[i*2+1]=clamp(this.rain[i]/.0025)*255}this.volumeTexture.needsUpdate=true;this.volumeMaterial.uniforms.uTime.value=this.time}
  private vorticity(x:number,y:number,z:number){const wx=(this.w[this.idx(x,y+1,z)]-this.w[this.idx(x,y-1,z)])/(2*DY)-(this.v[this.idx(x,y,z+1)]-this.v[this.idx(x,y,z-1)])/(2*DZ),wy=(this.u[this.idx(x,y,z+1)]-this.u[this.idx(x,y,z-1)])/(2*DZ)-(this.w[this.idx(x+1,y,z)]-this.w[this.idx(x-1,y,z)])/(2*DX),wz=(this.v[this.idx(x+1,y,z)]-this.v[this.idx(x-1,y,z)])/(2*DX)-(this.u[this.idx(x,y+1,z)]-this.u[this.idx(x,y-1,z)])/(2*DY);return Math.hypot(wx,wy,wz)}
  private updateField(){const p=this.fieldGeometry.getAttribute('position') as THREE.BufferAttribute,c=this.fieldGeometry.getAttribute('color') as THREE.BufferAttribute;let n=0;for(let z=0;z<NZ;z+=2)for(let y=0;y<NY;y+=2)for(let x=0;x<NX;x+=2){const i=this.idx(x,y,z),alt=z*DZ,temp=this.tempFromTheta(this.theta[i],alt),rh=clamp(this.q[i]/Math.max(.00001,this.qsat(temp,alt))),cold=clamp(this.cold[i]/8),vort=clamp(this.vorticity(x,y,z)/.02);p.setXYZ(n,x*DX/1000-W/2000,alt/1000,y*DY/1000-D/2000);if(this.field==='theta'){const q=clamp((temp+65)/105);c.setXYZ(n,.15+.8*q,.25+.45*(1-Math.abs(q-.5)*2),.9-.7*q)}else if(this.field==='moisture')c.setXYZ(n,.12+.15*rh,.25+.55*rh,.32+.6*rh);else if(this.field==='coldpool')c.setXYZ(n,.15+.65*clamp((this.theta[i]-this.thetaEnv(alt))/4),.2+.25*cold,.28+.72*cold);else c.setXYZ(n,.25+.75*vort,.18,.25+.7*(1-vort));n++}this.fieldGeometry.setDrawRange(0,n);p.needsUpdate=true;c.needsUpdate=true}
  private updateVectors(){const p=this.vectorGeometry.getAttribute('position') as THREE.BufferAttribute,c=this.vectorGeometry.getAttribute('color') as THREE.BufferAttribute;let n=0;for(let z=2;z<NZ-2;z+=4)for(let y=2;y<NY;y+=5)for(let x=2;x<NX;x+=5){const i=this.idx(x,y,z),uu=this.u[i],vv=this.v[i],ww=this.w[i],mag=Math.hypot(uu,vv,ww);if(mag<1)continue;const scale=clamp(mag*.045,.18,1.3),sx=x*DX/1000-W/2000,sy=z*DZ/1000,sz=y*DY/1000-D/2000,ex=sx+uu/mag*scale,ey=sy+ww/mag*scale,ez=sz+vv/mag*scale;p.setXYZ(n,sx,sy,sz);p.setXYZ(n+1,ex,ey,ez);const color=ww>1?[1,.45,.12]:ww<-1?[.2,.6,1]:[.7,.82,.86];c.setXYZ(n,...color as [number,number,number]);c.setXYZ(n+1,...color as [number,number,number]);n+=2}this.vectorGeometry.setDrawRange(0,n);p.needsUpdate=true;c.needsUpdate=true}

  private computeParcel(){const profile:ParcelPoint[]=[],dz=100;let temp=this.config.surfaceTemp+.5,q=this.config.rhSurface/100*this.qsat(temp,0),saturated=false,lcl:number|null=null,lfc:number|null=null,el:number|null=null,cape=0,cin=0;for(let z=0;z<=H;z+=dz){const sat=this.qsat(temp,z);if(q>=sat){saturated=true;q=sat;if(lcl===null)lcl=z/1000}const tv=(temp+273.15)*(1+.61*q),envT=this.temperatureEnv(z),envTv=(envT+273.15)*(1+.61*this.qEnv(z)),b=G*(tv-envTv)/envTv;if(lcl!==null&&lfc===null&&b>0)lfc=z/1000;if(lfc!==null&&el===null&&b<=0&&z/1000>lfc+.2)el=z/1000;if(lfc===null&&b<0)cin+=-b*dz;if(lfc!==null&&el===null&&b>0)cape+=b*dz;profile.push({z:z/1000,env:envT,parcel:temp,buoyancy:b});if(saturated){const tk=temp+273.15,gamma=G*(1+LV*sat/(RD*tk))/(CP+LV*LV*sat*EPS/(RD*tk*tk));temp-=gamma*dz}else temp-=.0098*dz;const mix=clamp(this.config.entrainment*.006,0,.02);temp=lerp(temp,this.temperatureEnv(z+dz),mix);q=lerp(q,this.qEnv(z+dz),mix)}return{profile,cape,cin,lcl,lfc,el}}
  sounding(){return this.cachedParcel}
  private updateLevels(){const lv=[this.cachedParcel.lcl,this.cachedParcel.lfc,this.cachedParcel.el];this.levelHelpers.forEach((h,i)=>{h.visible=lv[i]!==null;if(lv[i]!==null)h.position.y=lv[i]!})}
  private countCores(){const mask=new Uint8Array(NX*NY);for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){let active=false;for(let z=3;z<Math.min(NZ-2,11);z++){const i=this.idx(x,y,z);if(this.w[i]>2&&this.cloud[i]>.00007){active=true;break}}mask[x+NX*y]=active?1:0}let cores=0;const stack:number[]=[];for(let i=0;i<mask.length;i++){if(mask[i]!==1)continue;cores++;mask[i]=2;stack.push(i);while(stack.length){const a=stack.pop()!,x=a%NX,y=Math.floor(a/NX);for(const b of [mod(x+1,NX)+NX*y,mod(x-1,NX)+NX*y+x*0,x+NX*mod(y+1,NY),x+NX*mod(y-1,NY)])if(mask[b]===1){mask[b]=2;stack.push(b)}}}return cores}
  diagnostics(){let up=0,down=0,rainRate=0,top=0,coldMax=0,thermalTop=0,maxCloud=0;for(let z=0;z<NZ;z++)for(let y=0;y<NY;y++)for(let x=0;x<NX;x++){const i=this.idx(x,y,z),alt=z*DZ;up=Math.max(up,this.w[i]);down=Math.max(down,-this.w[i]);rainRate=Math.max(rainRate,this.rain[i]*12000);maxCloud=Math.max(maxCloud,this.cloud[i]);if(this.cloud[i]>.00007)top=Math.max(top,alt/1000);if(this.w[i]>.6)thermalTop=Math.max(thermalTop,alt/1000);if(alt<1500)coldMax=Math.max(coldMax,this.cold[i])}const cores=this.countCores(),shear=Math.hypot(...[this.windUV(6000)[0]-this.windUV(0)[0],this.windUV(6000)[1]-this.windUV(0)[1]] as [number,number]),cellType=coldMax>7&&up<2?'Outflow-dominant':cores>=3?'3D-мультиячейка':cores===2?'Две взаимодействующие ячейки':cores===1&&shear>18?'Наклонённая организованная ячейка':cores===1?'Одиночная 3D-ячейка':top>1?'Развивающийся 3D cumulus':'Термики пограничного слоя',cellReason=cores?`${cores} пространственно разделённых updraft-ядра`:'глубокое ядро ещё не сформировано';let logic='Трёхмерные термики перераспределяют тепло и влагу в пограничном слое.';if(top>=(this.cachedParcel.lcl??99))logic='На LCL объём воздуха насыщается; сухое вовлечение размывает края облака.';if(top>=(this.cachedParcel.lfc??99))logic='Выше LFC updraft ускоряется в объёме и наклоняется векторным сдвигом ветра.';if(top>=(this.cachedParcel.el??99)-.6)logic='У EL плавучесть исчезает: поток расходится во всех горизонтальных направлениях, формируя наковальню.';if(coldMax>3)logic+=coldMax>7?' Холодный купол подтекает под inflow и уничтожает исходное ядро.':' 3D gust front поднимает тёплый воздух на периферии cold pool.';if(this.microburstOutflow>8)logic+=' Нагруженный осадками downdraft создал радиально расходящийся микропорыв.';return{...this.cachedParcel,updraft:up,downdraft:down,rain:rainRate,cloudTop:top,thermalTop,cloudWater:maxCloud*1000,coldPool:coldMax,microburst:this.microburstOutflow,cellType,cellReason,logic,insolation:this.insolation()}}

  render(){const width=Math.max(2,this.canvas.clientWidth),height=Math.max(2,this.canvas.clientHeight);if(this.canvas.width!==Math.floor(width*Math.min(devicePixelRatio,1.5))||this.canvas.height!==Math.floor(height*Math.min(devicePixelRatio,1.5))){this.renderer.setSize(width,height,false);this.camera.aspect=width/height;this.camera.updateProjectionMatrix()}this.volumeMesh.visible=this.field==='composite';this.fieldPoints.visible=this.field!=='composite';this.flowPoints.visible=this.showVectors;this.vectorLines.visible=this.showVectors;if(this.volumeMesh.visible)this.updateVolume();if(this.field!=='composite'&&this.frame%3===0)this.updateField();if(this.showVectors&&this.frame%4===0)this.updateVectors();this.frame++;this.controls.update();this.renderer.render(this.scene,this.camera)}
}
